### ISSUE TITLE
Surprising things

### ISSUE THREAD

**Issue by zpeters** [zpeters/awesome-mississippi#3]
Things that you wouldn't expect from Mississippi

**Comment by ejwolfe** [comment]
I want to add the surprising things from the Mississippi Gulf that are detailed in this website: https://matadornetwork.com/notebook/13-things-didnt-know-mississippi-gulf-coast/.

**Comment by ejwolfe** [comment]
I've made a pull request #11 that includes the changes to the tablet of contents and adding the facts from the reference website.

**Comment by zpeters** [comment]
thank you
